// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_dj4RDdczfsLU6BMzUAurpVInj0l0i6A',
    appId: '1:860950322160:android:4d2bde328bef1be3979b35',
    messagingSenderId: '860950322160',
    projectId: 'bnchinamartt',
    storageBucket: 'bnchinamartt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbbFF5RNYBrQTo8XaTYMFfM4SoAvOW-fQ',
    appId: '1:860950322160:ios:e12ddda1ac948c11979b35',
    messagingSenderId: '860950322160',
    projectId: 'bnchinamartt',
    storageBucket: 'bnchinamartt.appspot.com',
    iosBundleId: 'com.example.bnchinamartt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBMIrzidUze5nYqjkM5x8Mlhu-bEL4a0o',
    appId: '1:860950322160:web:5207d3a055177e6b979b35',
    messagingSenderId: '860950322160',
    projectId: 'bnchinamartt',
    authDomain: 'bnchinamartt.firebaseapp.com',
    storageBucket: 'bnchinamartt.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbbFF5RNYBrQTo8XaTYMFfM4SoAvOW-fQ',
    appId: '1:860950322160:ios:e12ddda1ac948c11979b35',
    messagingSenderId: '860950322160',
    projectId: 'bnchinamartt',
    storageBucket: 'bnchinamartt.appspot.com',
    iosBundleId: 'com.example.bnchinamartt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBMIrzidUze5nYqjkM5x8Mlhu-bEL4a0o',
    appId: '1:860950322160:web:59b56bf2d7aa0021979b35',
    messagingSenderId: '860950322160',
    projectId: 'bnchinamartt',
    authDomain: 'bnchinamartt.firebaseapp.com',
    storageBucket: 'bnchinamartt.appspot.com',
  );

}